<?php

/**
 * Geocodes the given string.
 *
 * @param $searchstring
 *   A string representing a location to be geocoded, e.g. an address.
 *
 * @return \Geocoder\Model\Address|NULL
 *   The determined geocode if geocoding was successful, NULL otherwise.
 */
function geocoder_geocode($searchstring) {
  $geocoder = \Drupal::service('geocoder.provider');
  try {
    /** @var \Geocoder\Model\AddressCollection $geocode */
    $geocode = $geocoder->geocode($searchstring);
    return $geocode->first();
  } catch (Exception $e) {
    watchdog_exception('geocoder', $e);
  }
  return NULL;
}
